DOWNLOAD_DEST: /Users/user/Desktop
ENABLE_LIB_DOWNLOAD: true
ENABLE_PDF_DOWNLOAD: true
SERP_API_KEY: 52f37c511c9295acafcec6fceea456f9cd61ae8f3a14763990ca7825e5207506
ZOT_ID: '7032524'
ZOT_KEY: k7mQ33h42Gdr6ivrFFUVnv50
